import { type NextPage } from "next";
import Head from "next/head";
import Map, { Marker } from "react-map-gl";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const surfSpots = api.example.getAll.useQuery();

  console.log(process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen text-gray-400">
        <Map
          mapStyle="mapbox://styles/mapbox/dark-v9"
          mapboxAccessToken={process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
        >
          <Marker longitude={-100} latitude={40} anchor="bottom" />
        </Map>
      </main>
    </>
  );
};

export default Home;
