import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Map from "react-map-gl";
import { MapController } from "../components/MapController/MapController";
import { MapMarker } from "../components/MapMarker/MapMarker";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const [addMode, setAddMode] = useState(false);
  const [addSpotCoords, setAddSpotCoords] = useState({ x: 0, y: 0 });

  const handleAddButtonClick = () =>
    addMode ? setAddMode(false) : setAddMode(true);
  const cursor = addMode ? "cell" : "pointer";

  const surfSpots = api.example.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen text-sm text-white">
        <Map
          mapStyle="mapbox://styles/mapbox/dark-v9"
          mapboxAccessToken={process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
          initialViewState={{
            latitude: 49.2,
            longitude: -2.22,
            zoom: 5,
          }}
          cursor={cursor}
          dragPan={!addMode}
          onClick={(info) => {
            if (addMode) {
              setAddSpotCoords({ x: info.point.x, y: info.point.y });
            }
          }}
        >
          {surfSpots &&
            surfSpots.data?.map((surfSpot) => (
              <MapMarker surfSpot={surfSpot} key={surfSpot.name} />
            ))}
        </Map>
        <MapController
          addMode={addMode}
          handleAddButtonClick={handleAddButtonClick}
        />
        <div
          className="absolute -translate-y-full -translate-x-1/2 rounded-md bg-white p-4 text-black transition-all duration-300"
          style={{ top: addSpotCoords.y, left: addSpotCoords.x }}
        >
          <form
            onSubmit={(e) => {
              e.preventDefault();
              console.log("suuuh");
            }}
          >
            <button
              type="submit"
              className="flex items-center gap-x-2 rounded-md bg-indigo-600 p-4 font-medium text-white hover:bg-opacity-80"
            >
              <Image src="add.svg" width={24} height={24} alt="add" /> Add Surf
              Spot
            </button>{" "}
          </form>
        </div>
      </main>
    </>
  );
};

export default Home;
